version: '2'
services:
  kafka:
    image: flozano/kafka:0.9.0.0
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: kafka
  elasticsearch:
    image: nshou/elasticsearch-kibana:latest
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      transport.host: 0.0.0.0
    ports:
      - "9200:9200"
      - "5601:5601"
  importer:
    build: .
    depends_on:
      - elasticsearch
      - kafka
    volumes:
      - "./:/importer"
    working_dir: /importer
    entrypoint: "/importer/run_standalone.sh"
